#!/bin/bash
## theme=default

#  -V theme=default          \
# sky,beige,simple,serif,night,moon,solarized
#  --highlight-style=tango \
# pygments,kate,monochrome,espresso,haddock,tango,zenburn

pandoc -o presentation.html \
  -t revealjs               \
  -V theme=solarized          \
  --incremental             \
  --mathjax                 \
  --smart                   \
  --standalone              \
  presentation.md

# --include-after-body=client.js


#  --filter pandoc-citeproc  \
# presentation.yaml

#  --self-contained          \

# pandoc -o presentation.pdf  \
#   --from=markdown           \
#   --self-contained          \
#   --smart                   \
#   --standalone              \
#   presentation.md
